const SET_USER = 'SET_USER';
const SET_DATA = 'SET_DATA';
const SET_LOADING = 'SET_LOADING';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export default {
  SET_USER,
  SET_DATA,
  SET_LOADING,
  SET_CURRENT_PAGE,
  SET_TOTAL_PAGES,
};
